name: Deployment pipeline

on:
  push:
    branches:
      - master
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Check out the repository - 
      - uses: actions/setup-node@v3 # Set up Node.js
        with:
          node-version: '16'

      - name: Install dependencies # Install the dependencies 
        run: npm install
      - name: Check style
        run: npm run eslint  